/* 
 * iQX Amplify API Reference
 *
 * Welcome to the iQX Amplify API reference. This is a live example of how you can use [iQX Amplify](http://app.iqxamplify.com/) to integrate your own e-commerce store or ticketing engine.  The iQX Amplify API is organized around the [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer) mothodology, and it uses resource-oriented URLs, and common HTTP response codes to indicate API errors. All requests are authenticated using an `api-key` which can be obtained from your developer dashboard within iQX Amplify.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: development@iqxcorp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Pagination struct {

	// Number of results returned
	ObjectCount float32 `json:"object_count,omitempty"`

	// The current page number
	PageNumber float32 `json:"page_number,omitempty"`

	// Number of maximum items returned per page
	PageSize float32 `json:"page_size,omitempty"`

	// Total number of pages for the query
	PageCount float32 `json:"page_count,omitempty"`
}
